### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by abdulmalikkhan655** [ZeeRooo/MaterialFBook#172] opened 2018-05-12 10:55 UTC
Hello, @ZeeRoooI want to contribute in "MaterialFBook" so i  want to designed a new logo for "MaterialFBook" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

**Comment by ZeeRooo** [comment] 2018-05-12 12:54
A new logo would be great! Yes, i want it, send me your design please :)

**Comment by abdulmalikkhan655** [comment] 2018-05-12 19:05
hello sir check this logo and select your logo If there's something you want to change, I'll do it.
![32261044_1863390590372681_6784787565800062976_n](https://user-images.githubusercontent.com/36396753/39960594-05ade5ec-563f-11e8-85fc-13b2596c94dc.jpg)
![32294196_1863390620372678_1987990960881008640_n](https://user-images.githubusercontent.com/36396753/39960595-05ee29f4-563f-11e8-96fd-1aeee6d2f264.jpg)
![32384051_1863390623706011_3701619475318046720_n](https://user-images.githubusercontent.com/36396753/39960596-06508e0a-563f-11e8-8363-4778d1c8e82f.jpg)
![32350165_1863409100370830_1734694800742940672_n](https://user-images.githubusercontent.com/36396753/39960724-34b5b340-5641-11e8-8bf5-158cc9391c90.jpg)

**Comment by ZeeRooo** [comment] 2018-05-12 19:30
IMHO, this one is the best looking logo.
It would be nice if you put some transparency in the white background (80% opacity or so). And a little shadow below the icon.
![sin titulo](https://user-images.githubusercontent.com/19499008/39960905-98ea1922-5601-11e8-912e-080e76bb51c3.png)

**Comment by ggcarlosr** [comment] 2018-05-12 21:49
Hello friends, I can add a logo proposal, and you can have a second option to choose, can I contribute?

**Comment by ZeeRooo** [comment] 2018-05-12 23:55
@ggcarlosr Sure! Show us your design please :)

**Comment by abdulmalikkhan655** [comment] 2018-05-13 10:40
hello @ZeeRooo   this is final logo as your demands background (80% opacity or so). And a little shadow below the icon.
![32336924_1864024293642644_4112131096555028480_n](https://user-images.githubusercontent.com/36396753/39966336-aca53178-56c3-11e8-9ffa-91021a1e37ef.jpg)
![32469644_1864024286975978_842153798670483456_n](https://user-images.githubusercontent.com/36396753/39966337-acdf5128-56c3-11e8-8cef-d3425909f35b.jpg)

**Comment by ZeeRooo** [comment] 2018-05-13 15:33
I fell in love with the first option

**Comment by abdulmalikkhan655** [comment] 2018-05-14 04:01
![image](https://user-images.githubusercontent.com/36396753/39977692-1b93cf68-5755-11e8-884f-599216e243bc.png)

@ZeeRooo  sir here is google drive link you can download here all the files 
https://drive.google.com/drive/folders/1u3TubK4fMv_ykApMbDZGqdpnLtHZbBK9

**Comment by TacoTheDank** [comment] 2018-05-18 21:34
Hey @ZeeRooo 

not to burst your bubble, but... 
https://github.com/kaeptmblaubaer1000/android-torchlight/issues/3

**Comment by Bugsbane** [comment] 2018-06-26 08:29
Ok, first up, I'm not part of any crypto pyramid scheme that's going to pay me anything if you accept my logo design. I don't get anything beyond the warm fuzzies of seeing my work in an app I use regularly. You can look at my GitHub activity and see that I'm am open source contributor first and foremost.

So... that said, I wasn't exactly inspired by the designs above (ignoring that the second one is pretty much a straight duplicate of a design I did for another website once). Aside from being bland, branding yourself under "MF" is just asking for trouble. I mean, the first thing I think of, as an English speaker who rarely swears is - pardon me - "mother fucker".

So, anyway, I thought I'd submit another design. It would still need optimizing for smaller sizes. It's still very rough so I don't waste my time going in the wrong direction, but anyway, here's my idea, all hand drawn from scratch, FOSS friendly-like:

![material fbook icon](https://user-images.githubusercontent.com/401733/41898974-4111a79a-78f9-11e8-8871-a5c009e8f0a8.png)


It follows basic Material Design ideas, actually illustrates that it's to do with Face+Book (without saying FaceBook or using the actual FaceBook "f").

SVG available on request under whatever FOSS friendly license you wish.

**Comment by TacoTheDank** [comment] 2018-06-26 22:19
ten outta ten

**Comment by ZeeRooo** [comment] 2018-06-26 22:32
This design is amazing. Is pretty obvious but fresh and different at the
same time

**Comment by Bugsbane** [comment] 2018-09-15 05:38
Holy cow, sorry, I didn't see your comments back in... July? So would you like me to clean it up and submit a finalized SVG?

**Comment by ZeeRooo** [comment] 2018-09-15 06:00
Yes, it would be great :)

**Closed** 2018-12-26 05:34 UTC
Labels: enhancement
