### ISSUE TITLE
Messages don't sort correctly/not visible

### ISSUE THREAD

**Issue by alekksander** [ZeeRooo/MaterialFBook#128] opened 2017-12-15 20:00 UTC
Well… another bug report. I hope screenshot says it all, if not i'm eager to talk about it :)

![bb1](https://user-images.githubusercontent.com/3148302/34058321-e2329f1e-e1da-11e7-8150-12b409b1e5e5.jpg)

this happens on LG phone with android 5.1

**Comment by ZeeRooo** [comment] 2017-12-15 20:09
I have changed the refresh time of the badge icons (every 15s). If you are
in messages page it wont be displayed. Same for notifications, friends
request and most recent.

**Comment by alekksander** [comment] 2017-12-15 20:30
problem is something else. if i go to messages from app top blue bar it doesn't show latest and unread conversations. unread and latest appear only if i go to messages from facebooks blue bar

**Comment by ZeeRooo** [comment] 2017-12-15 20:36
This button load [https;//m.facebook.com/messages](url) so if there's a bug is from Facebook

**Comment by creativetrendsapps** [comment] 2018-01-01 18:11
@ZeeRooo I think this issue should be closed as this isn't actually an issue/bug.

**Comment by alekksander** [comment] 2018-01-01 18:21
depends on where You click, it loads different list of conversations. this is definitively something that shouldn't happen at all, but can be closed, as it's probly fb related, not app related issue. i'm okay with closing ;)

**Comment by ZeeRooo** [comment] 2018-01-06 01:09
Its extrange. Have you tried loading it from another client or browser?
The button load [https://m.facebook.com/messages](url) and the button in the Facebook topbar loads the same but with Javascript.
Imho, if there is a bug, it is from Facebook guys

**Comment by alekksander** [comment] 2018-01-11 10:01
tonight i experienced the bug on my phone. twice in a row, but cannot reproduce. as said before something has to be wrong on their side. however i stopped internet connection, and noticed that it doesn't go to https://github.com/ZeeRooo/MaterialFBook/issues/url exactly…

**Comment by ZeeRooo** [comment] 2018-01-11 16:28
Is the same. The extra string is because you are clicking a javascript button.
Please opem your browser, log in into FB and load both urls. Then tell me if the issue persist when you load _m.facebook.com/messages/_

**Comment by ZeeRooo** [comment] 2018-01-11 16:57
Ok. I could reproduce the error right now.
I have tried loading it in Chrome and the error still here (i'm happy
because is not MFB error). The fix is load the messages with javascript
function. I'll fix it later

**Comment by alekksander** [comment] 2018-01-11 16:59
okay, great to see You have finally put Your finger on it. Waiting for the fix. 
As always — Big Thanks!

**Comment by ZeeRooo** [comment] 2018-01-11 17:08
Have you tried the notification system? It is firing at time?

**Comment by alekksander** [comment] 2018-01-11 17:14
You mean MFB notifications? i'm not using it, but can test if You'd like me to.

**Comment by ZeeRooo** [comment] 2018-01-11 17:21
Yes, i'm talking about the built-in notification system.

**Comment by ZeeRooo** [comment] 2018-01-13 02:08
@alekksander Please try it and tell me if it's fixed: https://github.com/ZeeRooo/MaterialFBook/blob/Testing/MaterialFBook_3.6.8.apk?raw=true

**Comment by alekksander** [comment] 2018-01-13 11:15
it is fixed, but resolves new issues :(
**1. Build form link is not overdriving previous versions**
![version not overdriven](https://user-images.githubusercontent.com/3148302/34905536-f366ed30-f85a-11e7-81d9-2063ed7b72ed.jpg)

**2. Title of the previously visited place stays in messages** (visible also on third screen shot – saying newest (came ot messages from newest posts))
![minor title stays](https://user-images.githubusercontent.com/3148302/34905551-260ece56-f85b-11e7-8b1c-d2d77fc1eca6.jpg)

**3. Unread messages doubling itself** (present in on previous builds too when going to ?soft=messages. 99% percent their side failure)
![doubling](https://user-images.githubusercontent.com/3148302/34905565-6a07a77c-f85b-11e7-8378-4d2f6731db0e.png)

**Comment by alekksander** [comment] 2018-01-13 11:20
about the notification system – i'm not able to get it to work. some time ago i reported videos not loading due to netguard working in background. i think no notifications might be related, so probably not mfb bug, but my certain settings issue.

**Comment by ZeeRooo** [comment] 2018-01-13 12:20
1- Yes, the repeated messages is a bug from Facebook (also the old bug). It
happens when you are in messages and a new chat arrives, but i you refresh
the page it'll be normal. (You can see in any browser this bug).
2- The wrong package id is a wrong flag that i chose when to build the app,
sorry :p (it's a normal "issue" if you already have installed the version
from fdroid because they have another package id)
3- And for the title... Since it's a javascript page i have to change the
title manually :/

**Comment by ZeeRooo** [comment] 2018-01-20 04:29
Please try it: https://github.com/ZeeRooo/MaterialFBook/blob/master/apks/MaterialFBook_3.6.8.apk?raw=true

**Comment by alekksander** [comment] 2018-01-20 10:46
minor stuff: if messages is the url app starts with, it doesn't go to ?soft=messages

**Comment by ZeeRooo** [comment] 2018-01-20 13:45
The button doesnt load an url, it simulate the click on the Facebook
toolbar.
If you starts the app directly with messages option it loads: "
https://m.facebook.com/messages" (same as button in 3.6.7 and below)

**Closed** 2018-04-29 09:56 UTC
